- name: Download Terraform binary
  get_url:
    url: "https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip"
    dest: "/tmp/terraform.zip"
    mode: '0644'

- name: Unzip Terraform binary
  unarchive:
    src: "/tmp/terraform.zip"
    dest: "/usr/local/bin"
    remote_src: yes

- name: Remove downloaded terraform.zip
  file:
    path: "/tmp/terraform.zip"
    state: absent

- name: Verify Terraform installation
  command: terraform -v
  register: terraform_version
  failed_when: terraform_version.rc != 0
  changed_when: false

- name: Display Terraform version
  debug:
    msg: "Terraform version installed: {{ terraform_version.stdout }}"
