---
- name: Configure AWX environment and install kubectx & terraform
  hosts: all
  become: yes

  roles:
    - { role: kubectx_installation, tags: kubectx }
    - { role: terraform_installation, tags: terraform }
    # - { role: rancher_desktop_installation, tags: rancher }  # only if targeting Windows
