---
- name: Clone the kubectx repository
  shell: git clone https://github.com/ahmetb/kubectx /opt/kubectx
  args:
    executable: /bin/bash
    creates: /opt/kubectx

- name: Create symlink for kubectx
  file:
    src: /opt/kubectx/kubectx
    dest: /usr/local/bin/kubectx
    state: link

- name: Create symlink for kubens
  file:
    src: /opt/kubectx/kubens
    dest: /usr/local/bin/kubens
    state: link

